apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: airflow
spec:
  accessModes:
  - ReadWriteOnce 
  resources:  
    requests:
      storage: 40Gi
  storageClassName: ibmc-file-gold
  volumeMode: Filesystem 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-instance
  namespace: airflow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: ibmc-block-gold
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  
  resources:
    requests:
      storage: 40Gi
  storageClassName: ibmc-file-gold
  volumeMode: Filesystem
