apiversion: apps/v1
kind: Replicaset
metadata:
  name: my first rs
  labels:
    name: nginx 
spec:
  replicas: 3
  selectors:
    matchlabels:
      app: nginx
  template:  # this template details about pod 
    metadata:
      name: my first pod
      labels:
        app: nginx 
spec
  containers:
  - name: my first container
    image: nginx
    ports:
    - container port: 80          

 